import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';

export type Language = 'en' | 'fr' | 'es' | 'pt' | 'ar' | 'sw';

export const languageNames: Record<Language, string> = {
  en: 'English',
  fr: 'Français',
  es: 'Español',
  pt: 'Português',
  ar: 'العربية',
  sw: 'Kiswahili',
};

export const languageFlags: Record<Language, string> = {
  en: '🇺🇸',
  fr: '🇫🇷',
  es: '🇪🇸',
  pt: '🇧🇷',
  ar: '🇸🇦',
  sw: '🇰🇪',
};

interface LanguageState {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

// Translation dictionary with all 6 languages
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.onboarding': 'Onboarding',
    'nav.gallery': 'Gallery',
    'nav.contact': 'Contact',
    'nav.discover': 'Discover',
    'nav.workspaces': 'Workspaces',
    'nav.tools': 'Tools',
    'nav.enterprise': 'Enterprise',
    'nav.admin': 'Admin',
    'nav.quickLinks': 'Quick Links',
    'nav.howItWorks': 'How It Works',
    'nav.faq': 'FAQ',
    'nav.privacyPolicy': 'Privacy Policy',
    'nav.termsOfService': 'Terms of Service',
    'nav.pricing': 'Pricing',
    'nav.about': 'About',
    'nav.getStarted': 'Get Started',
    'nav.april': 'April AI',
    
    // Auth
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Register',
    'auth.signOut': 'Sign Out',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.credentialNumber': 'Credential Number',
    'auth.continueWithGoogle': 'Continue with Google',
    'auth.signUpWithGoogle': 'Sign up with Google',
    'auth.credential': 'Credential',
    'auth.google': 'Google',
    'auth.googleAccount': 'Google Account',
    'auth.credentialLogin': 'Credential Login',
    'auth.firstName': 'First Name',
    'auth.surname': 'Surname',
    'auth.gender': 'Gender',
    'auth.phone': 'Phone',
    'auth.country': 'Country',
    'auth.city': 'City',
    'auth.confirmPassword': 'Confirm',
    'auth.createAccount': 'Create Account',
    'auth.male': 'Male',
    'auth.female': 'Female',
    'auth.other': 'Other',
    'auth.needHelp': 'Need help?',
    'auth.or': 'or',
    'auth.checkingCredentials': 'Checking credentials...',
    'auth.invalidCredential': 'Invalid credential. Try: lago2.1B',
    'auth.invalidEmailPassword': 'Invalid email or password',
    'auth.redirectingGoogle': 'Redirecting to Google...',
    'auth.signingIn': 'Signing in...',
    'auth.invalidEmail': 'Invalid email format',
    'auth.accountCreated': 'Account Created!',
    'auth.redirectDashboard': 'Redirecting to your dashboard...',
    'auth.credentialSent': 'Your credential number has been sent to your email.',
    'auth.enterCredential': 'Enter your credential number',
    'auth.ownerHint': 'Enter lago2.1B for owner',
    'auth.enterPassword': 'Enter your password',
    'auth.useCredentialPassword': 'Owner: use your credential number as password',
    'auth.minChars': 'Min 6 chars',
    'auth.confirm': 'Confirm',
    'auth.networkError': 'Network error. Please try again.',
    'auth.emailRequired': 'Email is required',
    'auth.passwordMinLength': 'Password must be at least 6 characters',
    'auth.passwordMismatch': 'Passwords do not match',
    'auth.firstNameRequired': 'First name is required',
    'auth.registrationFailed': 'Registration failed',
    'auth.credentialInfo': 'By creating an account, you\'ll receive a credential number via email for future logins.',
    
    // Home Page
    'home.welcome': 'Welcome',
    'home.heroTitle': 'Build Your Professional Website',
    'home.heroSubtitle': 'Professional web solutions for your business',
    'home.startProject': 'Start Your Project',
    'home.learnMore': 'Learn More',
    'home.ourServices': 'Our Services',
    'home.ourPackages': 'Our Packages',
    'home.viewAllPackages': 'View All Packages',
    'home.getStarted': 'Get Started',
    'home.businessWebsites': 'Business Websites',
    'home.ecommerceStores': 'E-Commerce Stores',
    'home.bookingSystems': 'Booking Systems',
    'home.landingPages': 'Landing Pages',
    'home.webApplications': 'Web Applications',
    'home.websiteRedesign': 'Website Redesign',
    
    // Hero Section
    'hero.title': 'Find Businesses Without Websites',
    'hero.subtitle': 'Help them grow online with professional website development',
    'hero.description': 'Search any location worldwide, discover businesses lacking an online presence, and connect with them through our AI-powered outreach system.',
    'hero.searchPlaceholder': 'Enter city, area, or address...',
    'hero.searchButton': 'Search Businesses',
    'hero.allCategories': 'All Categories',
    'hero.businessesFound': 'Businesses Found',
    'hero.websitesCreated': 'Websites Created',
    'hero.countriesCovered': 'Countries Covered',
    'hero.enterLocation': 'Please enter a location',
    'hero.searchFailed': 'Failed to search businesses',
    'hero.connectionFailed': 'Failed to connect to search service',
    'hero.radius': 'Radius',
    
    // Services Section
    'services.title': 'What We Offer',
    'services.subtitle': 'Choose from our comprehensive range of web development services tailored to your business needs',
    'services.businessWebsites': 'Business Websites',
    'services.businessWebsitesDesc': 'Professional websites that showcase your brand and attract customers',
    'services.ecommerceStores': 'E-Commerce Stores',
    'services.ecommerceStoresDesc': 'Full-featured online stores to sell your products worldwide',
    'services.bookingSystems': 'Booking Systems',
    'services.bookingSystemsDesc': 'Online appointment and reservation systems for service businesses',
    'services.landingPages': 'Landing Pages',
    'services.landingPagesDesc': 'High-converting landing pages for marketing campaigns',
    'services.webApplications': 'Web Applications',
    'services.webApplicationsDesc': 'Custom web applications for your unique business needs',
    'services.websiteRedesign': 'Website Redesign',
    'services.websiteRedesignDesc': 'Modernize your existing website with a fresh new look',
    
    // Gallery
    'gallery.title': 'Stunning Websites We\'ve Built',
    'gallery.subtitle': 'Explore our portfolio of beautifully crafted websites across various industries',
    'gallery.ourWork': 'Our Work',
    'gallery.viewAllProjects': 'View All Projects',
    'gallery.portfolioTitle': 'Our Portfolio Gallery',
    'gallery.portfolioSubtitle': 'Explore our stunning website designs across various industries',
    'gallery.allProjects': 'All Projects',
    'gallery.tech': 'Technology',
    'gallery.healthcare': 'Healthcare',
    'gallery.filterBy': 'Filter by:',
    'gallery.loadMore': 'Load More Projects',
    'gallery.view': 'View',
    'gallery.ourPortfolio': 'Our Portfolio',
    'gallery.websiteDesign': 'Website Design',
    'gallery.ecommerce': 'E-Commerce',
    'gallery.landingPage': 'Landing Page',
    'gallery.portfolio': 'Portfolio',
    'gallery.blog': 'Blog',
    'gallery.businessSite': 'Business Site',
    
    // Packages
    'package.standard': 'Standard',
    'package.pro': 'Pro',
    'package.premium': 'Premium',
    'package.selectPackage': 'Select Package',
    'package.selected': 'Selected',
    'package.perProject': 'per project',
    'package.pricing': 'Pricing',
    'package.title': 'Choose Your Package',
    'package.subtitle': 'Select the perfect plan for your business needs. All packages include our premium support.',
    'package.mostPopular': 'Most Popular',
    'package.standardDesc': 'Perfect for small businesses starting their online journey',
    'package.proDesc': 'Ideal for growing businesses with advanced needs',
    'package.premiumDesc': 'Complete solution for established businesses',
    'package.needCustom': 'Need a custom solution?',
    'package.contactCustom': 'Contact Us for Custom Pricing',
    
    // Footer
    'footer.rights': 'All rights reserved.',
    'footer.needHelp': 'Need help? Contact',
    'footer.orCall': 'or call',
    'footer.ownedBy': 'Owned by',
    'footer.ourServices': 'Our Services',
    'footer.webDevelopment': 'Web Development',
    'footer.ecommerceSolutions': 'E-Commerce Solutions',
    'footer.seoOptimization': 'SEO Optimization',
    'footer.domainRegistration': 'Domain Registration',
    'footer.websiteMaintenance': 'Website Maintenance',
    'footer.description': 'We help businesses establish their online presence by connecting them with professional website development services.',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.submit': 'Submit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.preview': 'Preview',
    'common.previewMode': 'Preview Mode',
    'common.viewingAsUser': 'Viewing as User',
    'common.backToAdmin': 'Back to Admin',
    'common.fullAccess': 'Full Access',
    'common.projectPortal': 'Your Project Portal',
    'common.businessDiscovery': 'Business Discovery Platform',
    'common.userPortalPreview': 'User Portal Preview',
    'common.administrator': 'Administrator',
    
    // Language
    'language.english': 'English',
    'language.french': 'French',
    'language.spanish': 'Spanish',
    'language.portuguese': 'Portuguese',
    'language.arabic': 'Arabic',
    'language.swahili': 'Swahili',
    'language.selectLanguage': 'Select Language',
    
    // Login Page
    'login.title': 'WebFinder AI',
    'login.subtitle': 'Business Discovery Platform',
    'login.credentialTab': 'Credential',
    'login.emailTab': 'Email',
    'login.credentialPlaceholder': 'Enter lago2.1B for owner',
    'login.emailPlaceholder': 'brank493@gmail.com',
    'login.passwordPlaceholder': 'Use credential number as password',
    'login.signInButton': 'Sign In',
    'login.ownerHint': 'Owner',
    'login.needHelp': 'Need help?',
    'login.or': 'or',
    
    // Stats
    'stats.projectsDelivered': 'Projects Delivered',
    'stats.happyClients': 'Happy Clients',
    'stats.countriesServed': 'Countries Served',
    'stats.yearsExperience': 'Years Experience',
    'stats.projectsDone': 'Projects Done',
    'stats.clients': 'clients',
    
    // User Home Page
    'userHome.welcomeBack': 'Welcome back',
    'userHome.digitalJourney': 'Your Digital Journey',
    'userHome.startsHere': 'Starts Here',
    'userHome.heroDescription': 'Transform your business with stunning websites, powerful tools, and AI-powered solutions.',
    'userHome.viewPackages': 'View Packages',
    
    // About Section
    'about.title': 'About Us',
    'about.heading': 'Empowering Businesses with',
    'about.highlight': 'Digital Excellence',
    'about.paragraph1': 'WebFinder AI is a leading web development and business discovery platform.',
    'about.paragraph2': 'Our AI-powered platform combines cutting-edge technology with creative design.',
    'about.qualityFirst': 'Quality First',
    'about.qualityFirstDesc': 'Premium quality in every project',
    'about.clientFocused': 'Client Focused',
    'about.clientFocusedDesc': 'Your success is our priority',
    'about.onTimeDelivery': 'On-Time Delivery',
    'about.onTimeDeliveryDesc': 'Meeting deadlines, every time',
    'about.dedicatedSupport': 'Dedicated Support',
    'about.dedicatedSupportDesc': '24/7 assistance available',
    'about.learnMoreAboutUs': 'Learn More About Us',
    
    // Testimonials
    'testimonials.title': 'What Our Clients Say',
    'testimonials.subtitle': 'Don\'t just take our word for it - hear from our satisfied clients',
    
    // CTA Section
    'cta.title': 'Ready to Transform Your Business?',
    'cta.subtitle': 'Let\'s build something amazing together. Start your project today!',
    'cta.startProject': 'Start Your Project',
    'cta.callUsNow': 'Call Us Now',
    
    // Owner Dashboard
    'owner.previewUserHome': 'Preview User Home',
    'owner.domains': 'Domains',
    'owner.emailCampaigns': 'Email Campaigns',
    'owner.analytics': 'Analytics',
    'owner.team': 'Team',
    'owner.billing': 'Billing',
    'owner.notifications': 'Notifications',
    'owner.deployments': 'Deployments',
    'owner.editor': 'Editor',
    'owner.clientPortal': 'Client Portal',
    'owner.projectInfo': 'Project Information',
    'owner.updateProjectDetails': 'Update your project details and preferences',
    'owner.saveChangesReturn': 'Save Changes & Return Home',
    
    // Categories
    'category.all': 'All Categories',
    'category.restaurant': 'Restaurant',
    'category.retail': 'Retail',
    'category.health': 'Health & Medical',
    'category.beauty': 'Beauty & Spa',
    'category.auto': 'Auto Services',
    'category.service': 'Professional Services',
    'category.professional': 'Professional Services',
    'category.business': 'Business',
    'category.food': 'Food',
    'category.technology': 'Technology',
    'category.creative': 'Creative',
    
    // Registration
    'register.title': 'Create Your Account',
    'register.subtitle': 'Join WebFinder AI and start your digital journey',
    'register.tab': 'Register',
    'register.firstName': 'First Name',
    'register.firstNamePlaceholder': 'Enter your first name',
    'register.surname': 'Last Name',
    'register.surnamePlaceholder': 'Enter your last name',
    'register.emailPlaceholder': 'Enter your email address',
    'register.phonePlaceholder': 'Enter your phone number',
    'register.passwordPlaceholder': 'Create a password',
    'register.confirmPassword': 'Confirm Password',
    'register.confirmPasswordPlaceholder': 'Confirm your password',
    'register.gender': 'Gender',
    'register.selectGender': 'Select gender',
    'register.male': 'Male',
    'register.female': 'Female',
    'register.other': 'Other',
    'register.country': 'Country',
    'register.selectCountry': 'Select country',
    'register.city': 'City',
    'register.cityPlaceholder': 'Enter your city',
    'register.createAccount': 'Create Account',
    'register.creating': 'Creating Account...',
    'register.success': 'Account created successfully!',
    'register.error': 'Registration failed. Please try again.',
    'register.haveAccount': 'Already have an account?',
    'register.signIn': 'Sign In',
    
    // Countries
    'country.cameroon': 'Cameroon',
    'country.nigeria': 'Nigeria',
    'country.ghana': 'Ghana',
    'country.kenya': 'Kenya',
    'country.southAfrica': 'South Africa',
    'country.france': 'France',
    'country.uk': 'United Kingdom',
    'country.usa': 'United States',
    'country.canada': 'Canada',
    'country.germany': 'Germany',
    'country.other': 'Other',
    
    // Admin Dashboard
    'admin.title': 'Admin Dashboard',
    'admin.subtitle': 'Manage your business discovery platform',
    'admin.refresh': 'Refresh',
    'admin.totalBusinesses': 'Total Businesses',
    'admin.withoutWebsites': 'Without Websites',
    'admin.activeProjects': 'Active Projects',
    'admin.totalRevenue': 'Total Revenue',
    'admin.pendingPayments': 'Pending Payments',
    'admin.inProgress': 'In Progress',
    'admin.completed': 'Completed',
    'admin.recentProjects': 'Recent Projects',
    'admin.business': 'Business',
    'admin.package': 'Package',
    'admin.status': 'Status',
    'admin.payment': 'Payment',
    'admin.amount': 'Amount',
    'admin.date': 'Date',
    'admin.noCategory': 'No category',
    'admin.noProjects': 'No projects yet. Start discovering businesses to create projects.',
    
    // Analytics Dashboard
    'analytics.title': 'Analytics Dashboard',
    'analytics.subtitle': 'Track performance across all your websites and campaigns',
    'analytics.last7days': 'Last 7 days',
    'analytics.last30days': 'Last 30 days',
    'analytics.last90days': 'Last 90 days',
    'analytics.lastYear': 'Last year',
    'analytics.export': 'Export',
    'analytics.totalVisitors': 'Total Visitors',
    'analytics.pageViews': 'Page Views',
    'analytics.revenue': 'Revenue',
    'analytics.liveProjects': 'Live Projects',
    'analytics.inProgressCount': 'in progress',
    'analytics.fromLastMonth': 'from last month',
    'analytics.visitorsTrend': 'Visitors Trend',
    'analytics.avgVisitorsMonth': 'visitors/month',
    'analytics.growth': 'growth',
    'analytics.bounceRate': 'Bounce Rate',
    'analytics.decreasing': 'Decreasing (good)',
    'analytics.avgSessionDuration': 'Avg. Session Duration',
    'analytics.improvingEngagement': 'Improving engagement',
    'analytics.conversionRate': 'Conversion Rate',
    'analytics.aboveIndustryAvg': 'Above industry avg',
    'analytics.topPerformingProjects': 'Top Performing Projects',
    'analytics.views': 'views',
    'analytics.conversion': 'conversion',
    'analytics.live': 'Live',
    'analytics.trafficSources': 'Traffic Sources',
    'analytics.direct': 'Direct',
    'analytics.googleSearch': 'Google Search',
    'analytics.emailCampaigns': 'Email Campaigns',
    'analytics.socialMedia': 'Social Media',
    'analytics.referrals': 'Referrals',
    
    // Billing & Invoicing
    'billing.title': 'Billing & Invoices',
    'billing.subtitle': 'Manage invoices, payments, and billing',
    'billing.newInvoice': 'New Invoice',
    'billing.createInvoice': 'Create Invoice',
    'billing.createInvoiceDesc': 'Create a new invoice for a client',
    'billing.clientName': 'Client Name',
    'billing.clientNamePlaceholder': 'Enter client name',
    'billing.clientEmail': 'Client Email',
    'billing.clientEmailPlaceholder': 'Enter client email',
    'billing.projectName': 'Project Name',
    'billing.projectNamePlaceholder': 'Enter project name',
    'billing.packageLabel': 'Package',
    'billing.amountLabel': 'Amount ($)',
    'billing.totalRevenue': 'Total Revenue',
    'billing.pending': 'Pending',
    'billing.overdue': 'Overdue',
    'billing.draftInvoices': 'Draft Invoices',
    'billing.searchInvoices': 'Search invoices...',
    'billing.allInvoices': 'All Invoices',
    'billing.draft': 'Draft',
    'billing.sent': 'Sent',
    'billing.paid': 'Paid',
    'billing.invoices': 'Invoices',
    'billing.noInvoices': 'No invoices found',
    'billing.send': 'Send',
    'billing.markPaid': 'Mark Paid',
    'billing.remind': 'Remind',
    'billing.issued': 'Issued',
    'billing.due': 'Due',
    'billing.print': 'Print',
    'billing.downloadPdf': 'Download PDF',
    'billing.billTo': 'Bill To:',
    'billing.dueDate': 'Due Date:',
    'billing.total': 'Total:',
    'billing.description': 'Description',
    'billing.qty': 'Qty',
    'billing.price': 'Price',
    'billing.standardPackage': 'Standard ($149)',
    'billing.proPackage': 'Pro ($399)',
    'billing.premiumPackage': 'Premium ($999)',
    
    // Business List
    'business.searching': 'Searching for businesses...',
    'business.noResults': 'No businesses found yet',
    'business.useSearch': 'Use the search form above to discover businesses in your area.',
    'business.searchResults': 'Search Results',
    'business.found': 'Found',
    'business.businesses': 'businesses',
    'business.withoutWebsites': 'without websites',
    'business.withWebsites': 'with websites',
    'business.filter': 'Filter:',
    'business.allBusinesses': 'All Businesses',
    'business.noWebsite': 'No Website',
    'business.hasWebsite': 'Has Website',
    'business.businessName': 'Business Name',
    'business.category': 'Category',
    'business.rating': 'Rating',
    'business.address': 'Address',
    'business.websiteStatus': 'Website Status',
    'business.action': 'Action',
    'business.contact': 'Contact',
    'business.noWebsiteLabel': 'No Website',
    'business.hasWebsiteLabel': 'Has Website',
    'business.brokenLink': 'Broken Link',
    'business.socialOnly': 'Social Only',
    
    // Chat Panel
    'chat.assistant': 'WebFinder Assistant',
    'chat.chatWithAi': 'Chat with our AI',
    'chat.stars': 'stars',
    'chat.choosePackage': 'Choose your package:',
    'chat.selectPackage': 'Select',
    'chat.typeMessage': 'Type your message...',
    'chat.sorryError': 'Sorry, I had trouble processing your message. Please try again.',
    'chat.paymentError': 'Sorry, there was an issue processing your payment.',
    'chat.redirecting': "I'm redirecting you to complete the payment",
    'chat.greatChoice': 'Great choice!',
    'chat.receiveWorkspace': "You'll receive your workspace details shortly after.",
    
    // Domain Manager
    'domain.title': 'Domain Management',
    'domain.subtitle': 'Search, register, and manage domains for your clients',
    'domain.searchDomain': 'Search for a Domain',
    'domain.enterDomain': 'Enter a domain name (e.g., mybusiness)',
    'domain.search': 'Search',
    'domain.searchResults': 'Search Results',
    'domain.available': 'Available',
    'domain.taken': 'Taken',
    'domain.owned': 'Owned',
    'domain.pending': 'Pending',
    'domain.buy': 'Buy',
    'domain.purchaseDomain': 'Purchase Domain',
    'domain.purchaseDesc': 'You are about to purchase',
    'domain.domainLabel': 'Domain:',
    'domain.duration': 'Duration:',
    'domain.oneYear': '1 Year',
    'domain.sslCertificate': 'SSL Certificate:',
    'domain.includedFree': 'Included Free',
    'domain.totalLabel': 'Total:',
    'domain.completePurchase': 'Complete Purchase',
    'domain.notAvailable': 'Not available',
    'domain.yourDomains': 'Your Domains',
    'domain.noDomains': 'No domains registered yet',
    'domain.searchDomainAbove': 'Search for a domain above to get started',
    'domain.expires': 'Expires:',
    'domain.sslActive': 'SSL Active',
    'domain.visit': 'Visit',
    'domain.setupRequired': 'Setup Required',
    'domain.perYear': 'domain/year',
    'domain.sslFree': 'SSL Certificate',
    'domain.dnsSupport': 'DNS Support',
    
    // Email Campaigns
    'email.title': 'Email Campaigns',
    'email.subtitle': 'Create and manage email outreach campaigns',
    'email.newCampaign': 'New Campaign',
    'email.createCampaign': 'Create Email Campaign',
    'email.createCampaignDesc': 'Create a new email campaign to reach potential clients',
    'email.campaignName': 'Campaign Name',
    'email.campaignNamePlaceholder': 'e.g., Restaurant Outreach January',
    'email.subject': 'Email Subject',
    'email.subjectPlaceholder': 'e.g., Get your business online today!',
    'email.template': 'Template',
    'email.preview': 'Preview',
    'email.createCampaignButton': 'Create Campaign',
    'email.campaignsSent': 'Campaigns Sent',
    'email.totalRecipients': 'Total Recipients',
    'email.avgOpenRate': 'Avg Open Rate',
    'email.avgClickRate': 'Avg Click Rate',
    'email.campaigns': 'Campaigns',
    'email.recipients': 'recipients',
    'email.opens': 'opens',
    'email.clicks': 'clicks',
    'email.scheduled': 'Scheduled',
    'email.view': 'View',
    'email.analytics': 'Analytics',
    'email.emailTemplates': 'Email Templates',
    'email.createTemplate': 'Create Template',
    'email.duplicate': 'Duplicate',
    'email.edit': 'Edit',
    'email.initialOutreach': 'Initial Outreach',
    'email.followUp': 'Follow-up Email',
    'email.promotional': 'Promotional Offer',
    'email.welcome': 'Welcome Email',
    
    // Team Management
    'team.title': 'Team Management',
    'team.subtitle': 'Manage your team members and their permissions',
    'team.inviteMember': 'Invite Member',
    'team.inviteTeamMember': 'Invite Team Member',
    'team.inviteDesc': 'Send an invitation to add a new team member',
    'team.name': 'Name',
    'team.namePlaceholder': 'Enter name',
    'team.emailLabel': 'Email',
    'team.emailPlaceholder': 'Enter email address',
    'team.role': 'Role',
    'team.permissions': 'Permissions:',
    'team.sendInvitation': 'Send Invitation',
    'team.totalMembers': 'Total Members',
    'team.admins': 'Admins',
    'team.developers': 'Developers',
    'team.pendingInvites': 'Pending Invites',
    'team.teamMembers': 'Team Members',
    'team.joined': 'Joined:',
    'team.lastActive': 'Last active:',
    'team.projects': 'projects',
    'team.editTeamMember': 'Edit Team Member',
    'team.changeRoleFor': 'Change role for',
    'team.rolesPermissions': 'Roles & Permissions',
    'team.members': 'members',
    'team.allPermissions': 'All permissions',
    'team.manageTeam': 'Manage team',
    'team.manageProjects': 'Manage projects',
    'team.viewAnalytics': 'View analytics',
    'team.manageBilling': 'Manage billing',
    'team.createWebsites': 'Create websites',
    'team.editWebsites': 'Edit websites',
    'team.deployWebsites': 'Deploy websites',
    'team.viewProjects': 'View projects',
    'team.viewLeads': 'View leads',
    'team.createConversations': 'Create conversations',
    'team.pending': 'Pending',
    'team.cancel': 'Cancel',
    'team.admin': 'Admin',
    'team.developer': 'Developer',
    'team.sales': 'Sales',
    'team.viewer': 'Viewer',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.new': 'new',
    'notifications.all': 'All',
    'notifications.unread': 'Unread',
    'notifications.markAllRead': 'Mark all read',
    'notifications.total': 'Total',
    'notifications.read': 'Read',
    'notifications.unreadLabel': 'Unread',
    'notifications.messages': 'Messages',
    'notifications.recentNotifications': 'Recent Notifications',
    'notifications.noNotifications': 'No notifications',
    'notifications.notificationPreferences': 'Notification Preferences',
    'notifications.newMessages': 'New messages',
    'notifications.paymentNotifications': 'Payment notifications',
    'notifications.projectUpdates': 'Project updates',
    'notifications.alertsWarnings': 'Alerts and warnings',
    'notifications.systemUpdates': 'System updates',
    'notifications.enabled': 'Enabled',
    'notifications.disabled': 'Disabled',
    'notifications.markAsRead': 'Mark as read',
    'notifications.delete': 'Delete',
    
    // Deployment Center
    'deployment.title': 'Deployment Center',
    'deployment.subtitle': 'Deploy and manage your websites',
    'deployment.newDeployment': 'New Deployment',
    'deployment.liveSites': 'Live Sites',
    'deployment.totalVisits': 'Total Visits',
    'deployment.sslCertificates': 'SSL Certificates',
    'deployment.cdnEnabled': 'CDN Enabled',
    'deployment.activeDeployments': 'Active Deployments',
    'deployment.visits': 'visits',
    'deployment.building': 'Building...',
    'deployment.visitSite': 'Visit Site',
    'deployment.redeploy': 'Redeploy',
    'deployment.settings': 'Settings',
    'deployment.region': 'Region',
    'deployment.framework': 'Framework',
    'deployment.bandwidth': 'Bandwidth',
    'deployment.lastDeploy': 'Last Deploy',
    'deployment.buildLogs': 'Build Logs',
    'deployment.sslCertificate': 'SSL Certificate',
    'deployment.cdn': 'CDN',
    'deployment.analytics': 'Analytics',
    'deployment.deployProduction': 'Deploy a website to production',
    'deployment.readyToDeploy': 'Ready to Deploy',
    'deployment.projectsReady': 'You have projects ready for deployment',
    'deployment.deploy': 'Deploy',
    'deployment.buildingLabel': 'Building',
    'deployment.deploying': 'Deploying',
    'deployment.liveLabel': 'Live',
    'deployment.failed': 'Failed',
    'deployment.paused': 'Paused',
    
    // Onboarding
    'onboarding.choosePackage': 'Choose Package',
    'onboarding.selectPackage': 'Select your website package',
    'onboarding.yourBrief': 'Your Brief',
    'onboarding.tellUsProject': 'Tell us about your project',
    'onboarding.payment': 'Payment',
    'onboarding.completeOrder': 'Complete your order',
    'onboarding.thankYou': 'Thank You!',
    'onboarding.orderSubmitted': 'Your order has been submitted successfully.',
    'onboarding.whatHappensNext': 'What happens next:',
    'onboarding.reviewBrief': "We'll review your brief and requirements",
    'onboarding.verifyPayment': "We'll verify your payment and send confirmation",
    'onboarding.beginDevelopment': 'Our team will contact you to begin development',
    'onboarding.welcome': 'Welcome! Let\'s create your perfect website.',
    'onboarding.step1Title': 'Step 1: Choose Your Package',
    'onboarding.step1Desc': 'Select the package that best fits your business needs.',
    'onboarding.back': 'Back',
    'onboarding.continueToBrief': 'Continue to Brief',
    'onboarding.step2Title': 'Step 2: Tell Us About Your Project',
    'onboarding.oneTimePayment': 'one-time payment',
    'onboarding.changePackage': 'Change Package',
    'onboarding.step3Title': 'Step 3: Complete Your Payment',
    'onboarding.editBrief': 'Edit Brief',
    'onboarding.securePayment': 'Secure Payment',
    'onboarding.dataProtected': 'Your data is protected',
    'onboarding.quickDelivery': 'Quick Delivery',
    'onboarding.fastTurnaround': 'Fast turnaround time',
    'onboarding.support24/7': '24/7 Support',
    'onboarding.alwaysHelp': 'Always here to help',
    'onboarding.questions': 'Questions? Contact us at',
    'onboarding.or': 'or',
    'onboarding.professionalDev': 'Professional Website Development',
    
    // Workspace Manager
    'workspace.title': 'Workspace Manager',
    'workspace.subtitle': 'Manage your projects and workspaces',
    'workspace.newWorkspace': 'New Workspace',
    'workspace.active': 'Active',
    'workspace.archived': 'Archived',
    'workspace.noWorkspaces': 'No workspaces yet',
    'workspace.createFirst': 'Create your first workspace to get started',
    'workspace.projects': 'projects',
    'workspace.members': 'members',
    'workspace.created': 'Created',
    'workspace.lastActive': 'Last active',
    
    // Website Editor
    'editor.title': 'Website Editor',
    'editor.subtitle': 'Edit and customize your website',
    'editor.save': 'Save',
    'editor.preview': 'Preview',
    'editor.publish': 'Publish',
    'editor.undo': 'Undo',
    'editor.redo': 'Redo',
    'editor.desktop': 'Desktop',
    'editor.tablet': 'Tablet',
    'editor.mobile': 'Mobile',
    'editor.addSection': 'Add Section',
    'editor.sections': 'Sections',
    'editor.pages': 'Pages',
    'editor.settings': 'Settings',
    'editor.theme': 'Theme',
    'editor.styles': 'Styles',
    
    // Customer Portal
    'portal.title': 'Customer Portal',
    'portal.subtitle': 'View your project status and communicate with your team',
    'portal.myProjects': 'My Projects',
    'portal.messages': 'Messages',
    'portal.invoices': 'Invoices',
    'portal.support': 'Support',
    'portal.projectStatus': 'Project Status',
    'portal.lastUpdate': 'Last Update',
    'portal.viewDetails': 'View Details',
    
    // User Tracking Dashboard
    'tracking.title': 'Project Dashboard',
    'tracking.subtitle': 'Track your project progress and milestones',
    'tracking.progress': 'Progress',
    'tracking.milestones': 'Milestones',
    'tracking.updates': 'Updates',
    'tracking.timeline': 'Timeline',
    'tracking.files': 'Files',
    'tracking.notes': 'Notes',
    
    // Pricing Section
    'pricing.title': 'Pricing',
    'pricing.subtitle': 'Choose the perfect plan for your needs',
    'pricing.getStarted': 'Get Started',
    'pricing.contact': 'Contact Us',
    'pricing.popular': 'Most Popular',
    'pricing.features': 'Features',
    'pricing.monthly': 'Monthly',
    'pricing.yearly': 'Yearly',
    'pricing.save': 'Save',
    'pricing.transparent': 'Transparent Pricing',
    'pricing.oneTime': 'one-time',
    'pricing.needCustomSolution': 'Need a custom solution?',
    'pricing.contactUs': 'Contact us',
    'pricing.forEnterprisePricing': 'for enterprise pricing.',
    'pricing.includesEcommerce': 'Includes e-commerce & unlimited updates',
    
    // Package Showcase
    'packages.choosePlan': 'Choose Your Plan',
    'packages.allIncluded': 'All packages include',
    'packages.select': 'Select',
    'packages.currentPlan': 'Current Plan',
    
    // Payment
    'payment.selectMethod': 'Select Payment Method',
    'payment.mobileMoney': 'Mobile Money',
    'payment.creditCard': 'Credit Card',
    'payment.bankTransfer': 'Bank Transfer',
    'payment.crypto': 'Cryptocurrency',
    'payment.payWith': 'Pay with',
    'payment.completePayment': 'Complete Payment',
    'payment.processing': 'Processing...',
    'payment.secureCheckout': 'Secure Checkout',
    'payment.orderSummary': 'Order Summary',
    'payment.subtotal': 'Subtotal',
    'payment.tax': 'Tax',
    'payment.totalAmount': 'Total',
    
    // Client Brief Builder
    'brief.businessInfo': 'Business Information',
    'brief.tellUs': 'Tell us about your business',
    'brief.websiteGoals': 'Website Goals',
    'brief.whatDoYouWant': 'What do you want your website to achieve?',
    'brief.designPreferences': 'Design Preferences',
    'brief.howShouldItLook': 'How should it look?',
    'brief.additionalInfo': 'Additional Information',
    'brief.anythingElse': 'Anything else we should know?',
    'brief.continue': 'Continue',
    'brief.submit': 'Submit Brief',
    'brief.businessInfoDesc': 'Tell us about your business',
    'brief.designPages': 'Design & Pages',
    'brief.chooseStructure': 'Choose your website structure',
    'brief.featuresFunctionality': 'Features & Functionality',
    'brief.selectFeatures': 'Select features you need',
    'brief.timelineBudget': 'Timeline & Budget',
    'brief.finalDetails': 'Final details',
    'brief.businessName': 'Business Name',
    'brief.industry': 'Industry',
    'brief.description': 'Business Description',
    'brief.targetAudience': 'Target Audience',
    'brief.uniqueSelling': 'What makes you unique?',
    'brief.contactInformation': 'Contact Information',
    'brief.yourName': 'Your Name',
    'brief.fullName': 'Full name',
    'brief.emailAddress': 'Email',
    'brief.phoneWhatsapp': 'Phone/WhatsApp',
    
    // Template Selector
    'templates.chooseTemplate': 'Choose a Template',
    'templates.startFromScratch': 'Start from Scratch',
    'templates.preview': 'Preview',
    'templates.useTemplate': 'Use Template',
    'templates.categories': 'Categories',
    'templates.all': 'All',
    'templates.business': 'Business',
    'templates.portfolio': 'Portfolio',
    'templates.ecommerce': 'E-Commerce',
    'templates.blog': 'Blog',
    
    // Search Form
    'search.placeholder': 'Search...',
    'search.search': 'Search',
    'search.advanced': 'Advanced',
    'search.filters': 'Filters',
    'search.clearAll': 'Clear All',
    'search.results': 'results',
    'search.noResults': 'No results found',
    'searchForm.location': 'Location',
    'searchForm.enterCity': 'Enter city or address...',
    'searchForm.category': 'Category',
    'searchForm.selectCategory': 'Select category',
    'searchForm.radius': 'Radius',
    'searchForm.selectRadius': 'Select radius',
    'searchForm.discoverBusinesses': 'Discover Businesses',
    'searchForm.searching': 'Searching...',
    
    // Errors
    'error.somethingWentWrong': 'Something went wrong',
    'error.tryAgain': 'Please try again',
    'error.notFound': 'Not found',
    'error.unauthorized': 'Unauthorized access',
    'error.forbidden': 'Access forbidden',
    'error.serverError': 'Server error',
    
    // Success
    'success.saved': 'Saved successfully',
    'success.updated': 'Updated successfully',
    'success.deleted': 'Deleted successfully',
    'success.sent': 'Sent successfully',
    'success.created': 'Created successfully',
    
    // Time
    'time.minutesAgo': 'minutes ago',
    'time.hoursAgo': 'hours ago',
    'time.daysAgo': 'days ago',
    'time.weeksAgo': 'weeks ago',
    'time.monthsAgo': 'months ago',
    'time.yearsAgo': 'years ago',
    'time.justNow': 'Just now',
    'time.yesterday': 'Yesterday',
    'time.today': 'Today',
    'time.tomorrow': 'Tomorrow',
    
    // Activity Board
    'activity.title': 'Recent Activity',
    'activity.newLead': 'New lead',
    'activity.projectUpdate': 'Project update',
    'activity.paymentReceived': 'Payment received',
    'activity.websiteDeployed': 'Website deployed',
    'activity.viewAll': 'View All',
    
    // Activity Board Extended
    'activityBoard.title': 'Activity Board',
    'activityBoard.subtitle': 'Daily overview of all activities',
    'activityBoard.totalUsers': 'Total Users',
    'activityBoard.newToday': 'New Today',
    'activityBoard.payments': 'Payments',
    'activityBoard.revenue': 'Revenue',
    'activityBoard.aiActions': 'AI Actions',
    'activityBoard.websites': 'Websites',
    'activityBoard.messages': 'Messages',
    'activityBoard.activityFeed': 'Activity Feed',
    'activityBoard.realtimeDesc': 'Real-time activities from today',
    'activityBoard.noActivities': 'No activities recorded for this date',
    'activityBoard.activityBreakdown': 'Activity Breakdown',
    'activityBoard.userActivities': 'User Activities',
    'activityBoard.aiAgent': 'AI Agent',
    'activityBoard.quickActions': 'Quick Actions',
    'activityBoard.generateInvoice': 'Generate Invoice',
    'activityBoard.sendBulkEmail': 'Send Bulk Email',
    'activityBoard.exportUsers': 'Export Users',
    'activityBoard.runAprilTasks': 'Run April Tasks',
    'activityBoard.recentTransactions': 'Recent Transactions',
    'activityBoard.statusCompleted': 'Completed',
    'activityBoard.statusPending': 'Pending',
    'activityBoard.statusFailed': 'Failed',
    
    // Workspace Manager Extended
    'workspace.tabOverview': 'Overview',
    'workspace.tabBrief': 'Brief',
    'workspace.tabBuild': 'Build',
    'workspace.tabMessages': 'Messages',
    'workspace.statusLabel': 'Status',
    'workspace.paymentLabel': 'Payment',
    'workspace.businessDetails': 'Business Details',
    'workspace.categoryLabel': 'Category:',
    'workspace.emailLabel': 'Email:',
    'workspace.phoneLabel': 'Phone:',
    'workspace.addressLabel': 'Address:',
    'workspace.notAvailable': 'N/A',
    'workspace.startDevelopment': 'Start Development',
    'workspace.markComplete': 'Mark Complete',
    'workspace.servicesLabel': 'Services / Products',
    'workspace.servicesPlaceholder': 'What services does the business offer?',
    'workspace.designStyle': 'Design Style',
    'workspace.styleModern': 'Modern',
    'workspace.styleClassic': 'Classic',
    'workspace.styleMinimalist': 'Minimalist',
    'workspace.styleBold': 'Bold',
    'workspace.stylePlayful': 'Playful',
    'workspace.brandColors': 'Brand Colors (comma-separated)',
    'workspace.requiredFeatures': 'Required Features',
    'workspace.pagesNeeded': 'Pages Needed',
    'workspace.preferredDomain': 'Preferred Domain',
    'workspace.additionalNotes': 'Additional Notes',
    'workspace.saveBrief': 'Save Brief',
    'workspace.websiteBuilder': 'Website Builder',
    'workspace.packageLabel': 'Package',
    'workspace.builderDesc': 'Generate and customize the website using AI assistance.',
    'workspace.generateAI': 'Generate with AI',
    'workspace.clientCommunication': 'Client Communication',
    'workspace.messagePlaceholder': 'Type a message to the client...',
    'workspace.sendMessage': 'Send Message',
    'workspace.newProject': 'New Project',
    
    // Brief Builder Extended
    'brief.basicInfo': 'Basic Information',
    'brief.businessDesc': 'Business Description',
    'brief.selectBusinessType': 'Select business type',
    'brief.selectIndustry': 'Select your industry',
    'brief.selectRange': 'Select range',
    'brief.selectMethod': 'Select method',
    'brief.legalName': 'Legal Business Name (if different)',
    'brief.legalNamePlaceholder': 'Registered legal name',
    'brief.registrationNumber': 'Business Registration Number',
    'brief.registrationPlaceholder': 'Registration/License number',
    'brief.taxId': 'Tax ID / VAT Number',
    'brief.taxIdPlaceholder': 'Tax identification number',
    'brief.foundingYearPlaceholder': 'e.g., 2020',
    'brief.employeeCountLabel': 'Number of Employees',
    'brief.annualRevenueLabel': 'Annual Revenue',
    'brief.missionStatementLabel': 'Mission Statement',
    'brief.missionPlaceholder': 'What is your company\'s mission?',
    'brief.visionStatementLabel': 'Vision Statement',
    'brief.visionPlaceholder': 'Where do you see your company in the future?',
    'brief.coreValuesLabel': 'Core Values',
    'brief.coreValuesPlaceholder': 'e.g., Integrity, Innovation, Customer First',
    'brief.targetAudienceDescLabel': 'Target Audience Description *',
    'brief.targetAudiencePlaceholder': 'Who are your ideal customers? Describe their demographics, interests, behaviors...',
    'brief.targetAgeRangeLabel': 'Target Age Range',
    'brief.targetAgeRangePlaceholder': 'e.g., 25-45 years old',
    'brief.targetLocationLabel': 'Target Geographic Location',
    'brief.targetLocationPlaceholder': 'e.g., Cameroon, West Africa, Global',
    'brief.targetIncomeLabel': 'Target Income Level',
    'brief.targetIncomePlaceholder': 'e.g., Middle to upper class',
    'brief.goalsDifferentiation': 'Goals & Differentiation',
    'brief.primaryGoalsLabel': 'Primary Website Goals',
    'brief.primaryGoalsPlaceholder': 'What do you want to achieve with this website? e.g., Generate leads, sell products, build brand awareness...',
    'brief.uniqueSellingLabel': 'Unique Selling Proposition (USP)',
    'brief.uniqueSellingPlaceholder': 'What makes your business unique?',
    'brief.competitiveAdvantageLabel': 'Competitive Advantage',
    'brief.competitiveAdvantagePlaceholder': 'What gives you an edge over competitors?',
    'brief.brandPersonalityLabel': 'Brand Personality',
    'brief.brandPersonalityPlaceholder': 'e.g., Professional, Friendly, Innovative, Trustworthy',
    'brief.contactInfoSection': 'Contact Information',
    'brief.contactNameLabel': 'Contact Person Name *',
    'brief.contactNamePlaceholder': 'Full name',
    'brief.contactPositionLabel': 'Position/Title',
    'brief.contactPositionPlaceholder': 'e.g., CEO, Marketing Manager',
    'brief.primaryEmailLabel': 'Primary Email *',
    'brief.emailPlaceholder': 'email@example.com',
    'brief.alternativeEmailLabel': 'Alternative Email',
    'brief.alternativeEmailPlaceholder': 'backup@email.com',
    'brief.primaryPhoneLabel': 'Primary Phone',
    'brief.phonePlaceholder': '+237 6XX XXX XXX',
    'brief.alternativePhoneLabel': 'Alternative Phone',
    'brief.whatsappLabel': 'WhatsApp Number',
    'brief.preferredContactLabel': 'Preferred Contact Method',
    'brief.bestTimeLabel': 'Best Time to Contact',
    'brief.bestTimePlaceholder': 'e.g., Weekdays 9AM-5PM WAT',
    'brief.countryLabel': 'Country',
    'brief.countryPlaceholder': 'Cameroon',
    'brief.cityLabel': 'City',
    'brief.cityPlaceholder': 'Douala',
    'brief.addressLabel': 'Business Address',
    'brief.addressPlaceholder': 'Street address',
    'brief.postalCodeLabel': 'Postal Code',
    'brief.socialMediaSection': 'Social Media & Online Presence',
    'brief.currentWebsiteLabel': 'Current Website (if any)',
    'brief.currentWebsitePlaceholder': 'https://www.yourcurrentwebsite.com',
    'brief.facebookLabel': 'Facebook',
    'brief.facebookPlaceholder': 'https://facebook.com/yourpage',
    'brief.instagramLabel': 'Instagram',
    'brief.instagramPlaceholder': 'https://instagram.com/yourhandle',
    'brief.twitterLabel': 'Twitter/X',
    'brief.twitterPlaceholder': 'https://twitter.com/yourhandle',
    'brief.linkedinLabel': 'LinkedIn',
    'brief.linkedinPlaceholder': 'https://linkedin.com/company/yourcompany',
    'brief.youtubeLabel': 'YouTube',
    'brief.youtubePlaceholder': 'https://youtube.com/@yourchannel',
    'brief.tiktokLabel': 'TikTok',
    'brief.tiktokPlaceholder': 'https://tiktok.com/@yourhandle',
    'brief.otherSocialLabel': 'Other Social Media',
    'brief.technicalSection': 'Technical Requirements',
    'brief.competitors': 'Competitors',
    'brief.prev': 'Previous',
    'brief.nextStep': 'Next',
    'brief.submitBriefBtn': 'Submit Brief',
    'brief.successTitle': 'Brief Submitted Successfully!',
    'brief.successDesc': 'Thank you for submitting your website brief. We will review it and get back to you shortly.',
    'brief.downloadPdfBtn': 'Download as PDF',
    'brief.closeBtn': 'Close',
  },
  
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.dashboard': 'Tableau de bord',
    'nav.onboarding': 'Intégration',
    'nav.gallery': 'Galerie',
    'nav.contact': 'Contact',
    'nav.discover': 'Découvrir',
    'nav.workspaces': 'Espaces de travail',
    'nav.tools': 'Outils',
    'nav.enterprise': 'Entreprise',
    'nav.admin': 'Admin',
    'nav.quickLinks': 'Liens rapides',
    'nav.howItWorks': 'Comment ça marche',
    'nav.faq': 'FAQ',
    'nav.privacyPolicy': 'Politique de confidentialité',
    'nav.termsOfService': 'Conditions d\'utilisation',
    'nav.pricing': 'Tarifs',
    'nav.about': 'À propos',
    'nav.getStarted': 'Commencer',
    'nav.april': 'April IA',
    
    // Auth
    'auth.signIn': 'Se connecter',
    'auth.signUp': 'S\'inscrire',
    'auth.signOut': 'Se déconnecter',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.credentialNumber': 'Numéro d\'identifiant',
    'auth.continueWithGoogle': 'Continuer avec Google',
    'auth.signUpWithGoogle': 'S\'inscrire avec Google',
    'auth.credential': 'Identifiant',
    'auth.google': 'Google',
    'auth.googleAccount': 'Compte Google',
    'auth.credentialLogin': 'Connexion par identifiant',
    'auth.firstName': 'Prénom',
    'auth.surname': 'Nom',
    'auth.gender': 'Genre',
    'auth.phone': 'Téléphone',
    'auth.country': 'Pays',
    'auth.city': 'Ville',
    'auth.confirmPassword': 'Confirmer',
    'auth.createAccount': 'Créer un compte',
    'auth.male': 'Homme',
    'auth.female': 'Femme',
    'auth.other': 'Autre',
    'auth.needHelp': 'Besoin d\'aide?',
    'auth.or': 'ou',
    'auth.checkingCredentials': 'Vérification des identifiants...',
    'auth.invalidCredential': 'Identifiant invalide. Essayez: lago2.1B',
    'auth.invalidEmailPassword': 'Email ou mot de passe invalide',
    'auth.redirectingGoogle': 'Redirection vers Google...',
    'auth.signingIn': 'Connexion en cours...',
    'auth.invalidEmail': 'Format d\'email invalide',
    'auth.accountCreated': 'Compte créé!',
    'auth.redirectDashboard': 'Redirection vers votre tableau de bord...',
    'auth.credentialSent': 'Votre numéro d\'identifiant a été envoyé à votre email.',
    'auth.enterCredential': 'Entrez votre numéro d\'identifiant',
    'auth.ownerHint': 'Entrez lago2.1B pour propriétaire',
    'auth.enterPassword': 'Entrez votre mot de passe',
    'auth.useCredentialPassword': 'Propriétaire: utilisez votre numéro d\'identifiant comme mot de passe',
    'auth.minChars': 'Min 6 caractères',
    'auth.confirm': 'Confirmer',
    'auth.networkError': 'Erreur réseau. Veuillez réessayer.',
    'auth.emailRequired': 'L\'email est requis',
    'auth.passwordMinLength': 'Le mot de passe doit contenir au moins 6 caractères',
    'auth.passwordMismatch': 'Les mots de passe ne correspondent pas',
    'auth.firstNameRequired': 'Le prénom est requis',
    'auth.registrationFailed': 'Échec de l\'inscription',
    'auth.credentialInfo': 'En créant un compte, vous recevrez un numéro d\'identifiant par email.',
    
    // Home Page
    'home.welcome': 'Bienvenue',
    'home.heroTitle': 'Construisez votre site web professionnel',
    'home.heroSubtitle': 'Solutions web professionnelles pour votre entreprise',
    'home.startProject': 'Démarrer votre projet',
    'home.learnMore': 'En savoir plus',
    'home.ourServices': 'Nos services',
    'home.ourPackages': 'Nos forfaits',
    'home.viewAllPackages': 'Voir tous les forfaits',
    'home.getStarted': 'Commencer',
    'home.businessWebsites': 'Sites web d\'entreprise',
    'home.ecommerceStores': 'Boutiques en ligne',
    'home.bookingSystems': 'Systèmes de réservation',
    'home.landingPages': 'Pages d\'atterrissage',
    'home.webApplications': 'Applications web',
    'home.websiteRedesign': 'Refonte de site web',
    
    // Hero Section
    'hero.title': 'Trouvez des entreprises sans site web',
    'hero.subtitle': 'Aidez-les à se développer en ligne avec un développement web professionnel',
    'hero.description': 'Recherchez n\'importe quel lieu dans le monde, découvrez les entreprises sans présence en ligne.',
    'hero.searchPlaceholder': 'Entrez ville, zone ou adresse...',
    'hero.searchButton': 'Rechercher des entreprises',
    'hero.allCategories': 'Toutes les catégories',
    'hero.businessesFound': 'Entreprises trouvées',
    'hero.websitesCreated': 'Sites créés',
    'hero.countriesCovered': 'Pays couverts',
    'hero.enterLocation': 'Veuillez entrer un lieu',
    'hero.searchFailed': 'Échec de la recherche d\'entreprises',
    'hero.connectionFailed': 'Échec de la connexion au service de recherche',
    'hero.radius': 'Rayon',
    
    // Services Section
    'services.title': 'Ce que nous offrons',
    'services.subtitle': 'Choisissez parmi notre gamme complète de services de développement web',
    'services.businessWebsites': 'Sites web d\'entreprise',
    'services.businessWebsitesDesc': 'Sites web professionnels qui mettent en valeur votre marque',
    'services.ecommerceStores': 'Boutiques en ligne',
    'services.ecommerceStoresDesc': 'Boutiques complètes pour vendre vos produits dans le monde',
    'services.bookingSystems': 'Systèmes de réservation',
    'services.bookingSystemsDesc': 'Systèmes de rendez-vous en ligne pour les entreprises de services',
    'services.landingPages': 'Pages d\'atterrissage',
    'services.landingPagesDesc': 'Pages à fort taux de conversion pour vos campagnes marketing',
    'services.webApplications': 'Applications web',
    'services.webApplicationsDesc': 'Applications web personnalisées pour vos besoins uniques',
    'services.websiteRedesign': 'Refonte de site web',
    'services.websiteRedesignDesc': 'Modernisez votre site existant avec un nouveau look',
    
    // Gallery
    'gallery.title': 'Superbes sites web que nous avons créés',
    'gallery.subtitle': 'Explorez notre portfolio de sites web magnifiquement conçus',
    'gallery.ourWork': 'Notre travail',
    'gallery.viewAllProjects': 'Voir tous les projets',
    'gallery.portfolioTitle': 'Notre galerie de portfolio',
    'gallery.portfolioSubtitle': 'Explorez nos superbes conceptions de sites web',
    'gallery.allProjects': 'Tous les projets',
    'gallery.tech': 'Technologie',
    'gallery.healthcare': 'Santé',
    'gallery.filterBy': 'Filtrer par:',
    'gallery.loadMore': 'Charger plus de projets',
    'gallery.view': 'Voir',
    'gallery.ourPortfolio': 'Notre portfolio',
    'gallery.websiteDesign': 'Conception web',
    'gallery.ecommerce': 'E-Commerce',
    'gallery.landingPage': 'Page d\'atterrissage',
    'gallery.portfolio': 'Portfolio',
    'gallery.blog': 'Blog',
    'gallery.businessSite': 'Site d\'entreprise',
    
    // Packages
    'package.standard': 'Standard',
    'package.pro': 'Pro',
    'package.premium': 'Premium',
    'package.selectPackage': 'Sélectionner le forfait',
    'package.selected': 'Sélectionné',
    'package.perProject': 'par projet',
    'package.pricing': 'Tarifs',
    'package.title': 'Choisissez votre forfait',
    'package.subtitle': 'Sélectionnez le plan parfait pour les besoins de votre entreprise.',
    'package.mostPopular': 'Plus populaire',
    'package.standardDesc': 'Parfait pour les petites entreprises débutant en ligne',
    'package.proDesc': 'Idéal pour les entreprises en croissance avec des besoins avancés',
    'package.premiumDesc': 'Solution complète pour les entreprises établies',
    'package.needCustom': 'Besoin d\'une solution personnalisée?',
    'package.contactCustom': 'Contactez-nous pour un tarif personnalisé',
    
    // Footer
    'footer.rights': 'Tous droits réservés.',
    'footer.needHelp': 'Besoin d\'aide? Contactez',
    'footer.orCall': 'ou appelez',
    'footer.ownedBy': 'Propriété de',
    'footer.ourServices': 'Nos services',
    'footer.webDevelopment': 'Développement web',
    'footer.ecommerceSolutions': 'Solutions e-commerce',
    'footer.seoOptimization': 'Optimisation SEO',
    'footer.domainRegistration': 'Enregistrement de domaine',
    'footer.websiteMaintenance': 'Maintenance de site web',
    'footer.description': 'Nous aidons les entreprises à établir leur présence en ligne.',
    
    // Common
    'common.loading': 'Chargement...',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.submit': 'Soumettre',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.preview': 'Aperçu',
    'common.previewMode': 'Mode aperçu',
    'common.viewingAsUser': 'Visualisation en tant qu\'utilisateur',
    'common.backToAdmin': 'Retour à l\'admin',
    'common.fullAccess': 'Accès complet',
    'common.projectPortal': 'Votre portail de projet',
    'common.businessDiscovery': 'Plateforme de découverte d\'entreprises',
    'common.userPortalPreview': 'Aperçu du portail utilisateur',
    'common.administrator': 'Administrateur',
    
    // Language
    'language.english': 'Anglais',
    'language.french': 'Français',
    'language.spanish': 'Espagnol',
    'language.portuguese': 'Portugais',
    'language.arabic': 'Arabe',
    'language.swahili': 'Swahili',
    'language.selectLanguage': 'Sélectionner la langue',
    
    // Login Page
    'login.title': 'WebFinder AI',
    'login.subtitle': 'Plateforme de découverte d\'entreprises',
    'login.credentialTab': 'Identifiant',
    'login.emailTab': 'Email',
    'login.credentialPlaceholder': 'Entrez lago2.1B pour propriétaire',
    'login.emailPlaceholder': 'brank493@gmail.com',
    'login.passwordPlaceholder': 'Utilisez le numéro d\'identifiant comme mot de passe',
    'login.signInButton': 'Se connecter',
    'login.ownerHint': 'Propriétaire',
    'login.needHelp': 'Besoin d\'aide?',
    'login.or': 'ou',
    
    // Stats
    'stats.projectsDelivered': 'Projets livrés',
    'stats.happyClients': 'Clients satisfaits',
    'stats.countriesServed': 'Pays servis',
    'stats.yearsExperience': 'Années d\'expérience',
    'stats.projectsDone': 'Projets réalisés',
    'stats.clients': 'clients',
    
    // User Home Page
    'userHome.welcomeBack': 'Bienvenue',
    'userHome.digitalJourney': 'Votre parcours numérique',
    'userHome.startsHere': 'Commence ici',
    'userHome.heroDescription': 'Transformez votre entreprise avec des sites web spectaculaires.',
    'userHome.viewPackages': 'Voir les forfaits',
    
    // About Section
    'about.title': 'À propos de nous',
    'about.heading': 'Donner du pouvoir aux entreprises avec',
    'about.highlight': 'L\'excellence numérique',
    'about.paragraph1': 'WebFinder AI est une plateforme leader de développement web.',
    'about.paragraph2': 'Notre plateforme propulsée par l\'IA combine technologie de pointe et design créatif.',
    'about.qualityFirst': 'Qualité d\'abord',
    'about.qualityFirstDesc': 'Qualité premium dans chaque projet',
    'about.clientFocused': 'Centré sur le client',
    'about.clientFocusedDesc': 'Votre succès est notre priorité',
    'about.onTimeDelivery': 'Livraison à temps',
    'about.onTimeDeliveryDesc': 'Respect des délais, à chaque fois',
    'about.dedicatedSupport': 'Support dédié',
    'about.dedicatedSupportDesc': 'Assistance 24/7 disponible',
    'about.learnMoreAboutUs': 'En savoir plus sur nous',
    
    // Testimonials
    'testimonials.title': 'Ce que disent nos clients',
    'testimonials.subtitle': 'Ne nous croyez pas sur parole - écoutez nos clients satisfaits',
    
    // CTA Section
    'cta.title': 'Prêt à transformer votre entreprise?',
    'cta.subtitle': 'Construisons quelque chose d\'incroyable ensemble. Commencez votre projet aujourd\'hui!',
    'cta.startProject': 'Démarrer votre projet',
    'cta.callUsNow': 'Appelez-nous maintenant',
    
    // Owner Dashboard
    'owner.previewUserHome': 'Aperçu utilisateur',
    'owner.domains': 'Domaines',
    'owner.emailCampaigns': 'Campagnes email',
    'owner.analytics': 'Analytique',
    'owner.team': 'Équipe',
    'owner.billing': 'Facturation',
    'owner.notifications': 'Notifications',
    'owner.deployments': 'Déploiements',
    'owner.editor': 'Éditeur',
    'owner.clientPortal': 'Portail client',
    'owner.projectInfo': 'Informations du projet',
    'owner.updateProjectDetails': 'Mettez à jour les détails de votre projet',
    'owner.saveChangesReturn': 'Enregistrer et retourner',
    
    // Categories
    'category.all': 'Toutes les catégories',
    'category.restaurant': 'Restaurant',
    'category.retail': 'Commerce de détail',
    'category.health': 'Santé & Médical',
    'category.beauty': 'Beauté & Spa',
    'category.auto': 'Services auto',
    'category.service': 'Services professionnels',
    'category.professional': 'Services professionnels',
    'category.business': 'Entreprise',
    'category.food': 'Alimentation',
    'category.technology': 'Technologie',
    'category.creative': 'Créatif',
    
    // Registration
    'register.title': 'Créer votre compte',
    'register.subtitle': 'Rejoignez WebFinder AI et commencez votre parcours numérique',
    'register.tab': 'S\'inscrire',
    'register.firstName': 'Prénom',
    'register.firstNamePlaceholder': 'Entrez votre prénom',
    'register.surname': 'Nom',
    'register.surnamePlaceholder': 'Entrez votre nom',
    'register.emailPlaceholder': 'Entrez votre email',
    'register.phonePlaceholder': 'Entrez votre téléphone',
    'register.passwordPlaceholder': 'Créez un mot de passe',
    'register.confirmPassword': 'Confirmer le mot de passe',
    'register.confirmPasswordPlaceholder': 'Confirmez votre mot de passe',
    'register.gender': 'Genre',
    'register.selectGender': 'Sélectionner le genre',
    'register.male': 'Homme',
    'register.female': 'Femme',
    'register.other': 'Autre',
    'register.country': 'Pays',
    'register.selectCountry': 'Sélectionner le pays',
    'register.city': 'Ville',
    'register.cityPlaceholder': 'Entrez votre ville',
    'register.createAccount': 'Créer un compte',
    'register.creating': 'Création du compte...',
    'register.success': 'Compte créé avec succès!',
    'register.error': 'Échec de l\'inscription. Veuillez réessayer.',
    'register.haveAccount': 'Vous avez déjà un compte?',
    'register.signIn': 'Se connecter',
    
    // Countries
    'country.cameroon': 'Cameroun',
    'country.nigeria': 'Nigéria',
    'country.ghana': 'Ghana',
    'country.kenya': 'Kenya',
    'country.southAfrica': 'Afrique du Sud',
    'country.france': 'France',
    'country.uk': 'Royaume-Uni',
    'country.usa': 'États-Unis',
    'country.canada': 'Canada',
    'country.germany': 'Allemagne',
    'country.other': 'Autre',
    
    // Admin Dashboard
    'admin.title': 'Tableau de bord Admin',
    'admin.subtitle': 'Gérez votre plateforme de découverte d\'entreprises',
    'admin.refresh': 'Actualiser',
    'admin.totalBusinesses': 'Total entreprises',
    'admin.withoutWebsites': 'Sans site web',
    'admin.activeProjects': 'Projets actifs',
    'admin.totalRevenue': 'Revenu total',
    'admin.pendingPayments': 'Paiements en attente',
    'admin.inProgress': 'En cours',
    'admin.completed': 'Terminé',
    'admin.recentProjects': 'Projets récents',
    'admin.business': 'Entreprise',
    'admin.package': 'Forfait',
    'admin.status': 'Statut',
    'admin.payment': 'Paiement',
    'admin.amount': 'Montant',
    'admin.date': 'Date',
    'admin.noCategory': 'Pas de catégorie',
    'admin.noProjects': 'Pas encore de projets. Commencez à découvrir des entreprises.',
    
    // Analytics Dashboard
    'analytics.title': 'Tableau de bord analytique',
    'analytics.subtitle': 'Suivez les performances de tous vos sites web',
    'analytics.last7days': '7 derniers jours',
    'analytics.last30days': '30 derniers jours',
    'analytics.last90days': '90 derniers jours',
    'analytics.lastYear': 'Dernière année',
    'analytics.export': 'Exporter',
    'analytics.totalVisitors': 'Total visiteurs',
    'analytics.pageViews': 'Pages vues',
    'analytics.revenue': 'Revenus',
    'analytics.liveProjects': 'Projets en ligne',
    'analytics.inProgressCount': 'en cours',
    'analytics.fromLastMonth': 'par rapport au mois dernier',
    'analytics.visitorsTrend': 'Tendance des visiteurs',
    'analytics.avgVisitorsMonth': 'visiteurs/mois',
    'analytics.growth': 'croissance',
    'analytics.bounceRate': 'Taux de rebond',
    'analytics.decreasing': 'En baisse (bon)',
    'analytics.avgSessionDuration': 'Durée moyenne de session',
    'analytics.improvingEngagement': 'Engagement en amélioration',
    'analytics.conversionRate': 'Taux de conversion',
    'analytics.aboveIndustryAvg': 'Au-dessus de la moyenne',
    'analytics.topPerformingProjects': 'Projets les plus performants',
    'analytics.views': 'vues',
    'analytics.conversion': 'conversion',
    'analytics.live': 'En ligne',
    'analytics.trafficSources': 'Sources de trafic',
    'analytics.direct': 'Direct',
    'analytics.googleSearch': 'Recherche Google',
    'analytics.emailCampaigns': 'Campagnes email',
    'analytics.socialMedia': 'Réseaux sociaux',
    'analytics.referrals': 'Références',
    
    // Billing
    'billing.title': 'Facturation & Factures',
    'billing.subtitle': 'Gérez les factures, paiements et facturation',
    'billing.newInvoice': 'Nouvelle facture',
    'billing.createInvoice': 'Créer une facture',
    'billing.totalRevenue': 'Revenu total',
    'billing.pending': 'En attente',
    'billing.overdue': 'En retard',
    'billing.invoices': 'Factures',
    'billing.paid': 'Payé',
    'billing.draft': 'Brouillon',
    'billing.sent': 'Envoyé',
    
    // Business
    'business.searching': 'Recherche d\'entreprises...',
    'business.noResults': 'Aucune entreprise trouvée',
    'business.useSearch': 'Utilisez le formulaire ci-dessus pour découvrir des entreprises.',
    'business.searchResults': 'Résultats de recherche',
    'business.found': 'Trouvé',
    'business.businesses': 'entreprises',
    'business.withoutWebsites': 'sans site web',
    'business.withWebsites': 'avec site web',
    'business.filter': 'Filtrer:',
    'business.allBusinesses': 'Toutes les entreprises',
    'business.noWebsite': 'Pas de site',
    'business.hasWebsite': 'A un site',
    'business.contact': 'Contacter',
    
    // Chat Panel
    'chat.assistant': 'Assistant WebFinder',
    'chat.chatWithAi': 'Discutez avec notre IA',
    'chat.typeMessage': 'Tapez votre message...',
    'chat.greatChoice': 'Excellent choix!',
    
    // Domain Manager
    'domain.title': 'Gestion des domaines',
    'domain.subtitle': 'Recherchez, enregistrez et gérez les domaines',
    'domain.searchDomain': 'Rechercher un domaine',
    'domain.search': 'Rechercher',
    'domain.available': 'Disponible',
    'domain.taken': 'Pris',
    'domain.buy': 'Acheter',
    'domain.yourDomains': 'Vos domaines',
    
    // Email Campaigns
    'email.title': 'Campagnes email',
    'email.subtitle': 'Créez et gérez des campagnes de prospection email',
    'email.newCampaign': 'Nouvelle campagne',
    'email.campaigns': 'Campagnes',
    
    // Team Management
    'team.title': 'Gestion d\'équipe',
    'team.subtitle': 'Gérez les membres de votre équipe et leurs permissions',
    'team.inviteMember': 'Inviter un membre',
    'team.teamMembers': 'Membres de l\'équipe',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.all': 'Tout',
    'notifications.unread': 'Non lu',
    'notifications.markAllRead': 'Tout marquer comme lu',
    
    // Deployment
    'deployment.title': 'Centre de déploiement',
    'deployment.subtitle': 'Déployez et gérez vos sites web',
    'deployment.liveSites': 'Sites en ligne',
    'deployment.deploy': 'Déployer',
    'deployment.liveLabel': 'En ligne',
    
    // Onboarding
    'onboarding.choosePackage': 'Choisir le forfait',
    'onboarding.payment': 'Paiement',
    'onboarding.thankYou': 'Merci!',
    'onboarding.back': 'Retour',
    
    // Workspace
    'workspace.title': 'Gestionnaire d\'espace',
    'workspace.newWorkspace': 'Nouvel espace',
    'workspace.active': 'Actif',
    
    // Pricing
    'pricing.title': 'Tarifs',
    'pricing.getStarted': 'Commencer',
    'pricing.oneTime': 'unique',
    'pricing.transparent': 'Tarification transparente',
    
    // Payment
    'payment.selectMethod': 'Sélectionner le mode de paiement',
    'payment.mobileMoney': 'Mobile Money',
    'payment.creditCard': 'Carte de crédit',
    'payment.completePayment': 'Finaliser le paiement',
    'payment.processing': 'Traitement...',
    
    // Search
    'search.placeholder': 'Rechercher...',
    'search.search': 'Rechercher',
    'search.noResults': 'Aucun résultat',
    
    // Errors
    'error.somethingWentWrong': 'Une erreur est survenue',
    'error.tryAgain': 'Veuillez réessayer',
    
    // Success
    'success.saved': 'Enregistré avec succès',
    'success.updated': 'Mis à jour avec succès',
    
    // Time
    'time.minutesAgo': 'minutes',
    'time.hoursAgo': 'heures',
    'time.daysAgo': 'jours',
    'time.justNow': 'À l\'instant',
    'time.today': 'Aujourd\'hui',
    'time.yesterday': 'Hier',
    
    // Activity
    'activity.title': 'Activité récente',
    'activity.viewAll': 'Voir tout',
    
    // Activity Board Extended
    'activityBoard.title': 'Tableau d\'activité',
    'activityBoard.subtitle': 'Vue quotidienne de toutes les activités',
    'activityBoard.totalUsers': 'Total utilisateurs',
    'activityBoard.newToday': 'Nouveaux aujourd\'hui',
    'activityBoard.payments': 'Paiements',
    'activityBoard.revenue': 'Revenus',
    'activityBoard.aiActions': 'Actions IA',
    'activityBoard.websites': 'Sites web',
    'activityBoard.messages': 'Messages',
    'activityBoard.activityFeed': 'Flux d\'activité',
    'activityBoard.realtimeDesc': 'Activités en temps réel d\'aujourd\'hui',
    'activityBoard.noActivities': 'Aucune activité enregistrée pour cette date',
    'activityBoard.activityBreakdown': 'Répartition des activités',
    'activityBoard.userActivities': 'Activités utilisateurs',
    'activityBoard.aiAgent': 'Agent IA',
    'activityBoard.quickActions': 'Actions rapides',
    'activityBoard.generateInvoice': 'Générer une facture',
    'activityBoard.sendBulkEmail': 'Envoyer un email groupé',
    'activityBoard.exportUsers': 'Exporter les utilisateurs',
    'activityBoard.runAprilTasks': 'Exécuter les tâches April',
    'activityBoard.recentTransactions': 'Transactions récentes',
    'activityBoard.statusCompleted': 'Terminé',
    'activityBoard.statusPending': 'En attente',
    'activityBoard.statusFailed': 'Échoué',
    
    // Workspace Manager Extended
    'workspace.tabOverview': 'Aperçu',
    'workspace.tabBrief': 'Brief',
    'workspace.tabBuild': 'Construire',
    'workspace.tabMessages': 'Messages',
    'workspace.statusLabel': 'Statut',
    'workspace.paymentLabel': 'Paiement',
    'workspace.businessDetails': 'Détails de l\'entreprise',
    'workspace.categoryLabel': 'Catégorie:',
    'workspace.emailLabel': 'Email:',
    'workspace.phoneLabel': 'Téléphone:',
    'workspace.addressLabel': 'Adresse:',
    'workspace.notAvailable': 'N/D',
    'workspace.startDevelopment': 'Démarrer le développement',
    'workspace.markComplete': 'Marquer terminé',
    'workspace.servicesLabel': 'Services / Produits',
    'workspace.servicesPlaceholder': 'Quels services l\'entreprise offre-t-elle?',
    'workspace.designStyle': 'Style de design',
    'workspace.styleModern': 'Moderne',
    'workspace.styleClassic': 'Classique',
    'workspace.styleMinimalist': 'Minimaliste',
    'workspace.styleBold': 'Audacieux',
    'workspace.stylePlayful': 'Ludique',
    'workspace.brandColors': 'Couleurs de marque (séparées par des virgules)',
    'workspace.requiredFeatures': 'Fonctionnalités requises',
    'workspace.pagesNeeded': 'Pages nécessaires',
    'workspace.preferredDomain': 'Domaine préféré',
    'workspace.additionalNotes': 'Notes supplémentaires',
    'workspace.saveBrief': 'Enregistrer le brief',
    'workspace.websiteBuilder': 'Créateur de site web',
    'workspace.packageLabel': 'Forfait',
    'workspace.builderDesc': 'Générez et personnalisez le site web avec l\'assistance IA.',
    'workspace.generateAI': 'Générer avec IA',
    'workspace.clientCommunication': 'Communication client',
    'workspace.messagePlaceholder': 'Tapez un message au client...',
    'workspace.sendMessage': 'Envoyer le message',
    'workspace.newProject': 'Nouveau projet',
    'workspace.noWorkspaces': 'Pas encore d\'espaces de travail',
    'workspace.createFirst': 'Créez votre premier espace de travail',
    
    // Brief Builder Extended (French)
    'brief.step1': 'Infos entreprise',
    'brief.step2': 'Design & Pages',
    'brief.step3': 'Fonctionnalités',
    'brief.step4': 'Technique',
    'brief.step5': 'SEO & Marketing',
    'brief.step6': 'Ressources de marque',
    'brief.step7': 'Concurrents',
    'brief.step8': 'Délai & Budget',
    'brief.legalBusinessName': 'Nom légal de l\'entreprise',
    'brief.businessType': 'Type d\'entreprise',
    'brief.foundingYear': 'Année de création',
    'brief.employeeCount': 'Nombre d\'employés',
    'brief.annualRevenue': 'Chiffre d\'affaires annuel',
    'brief.businessDescription': 'Description de l\'entreprise',
    'brief.describeBusiness': 'Décrivez ce que fait votre entreprise...',
    'brief.targetAudienceDesc': 'Qui sont vos clients idéaux?',
    'brief.uniqueSellingDesc': 'Qu\'est-ce qui vous distingue des concurrents?',
    'brief.currentWebsite': 'URL du site actuel',
    'brief.primaryGoals': 'Objectifs principaux',
    'brief.secondaryGoals': 'Objectifs secondaires',
    'brief.designPreferencesDesc': 'Comment votre site web devrait-il ressembler?',
    'brief.styleModernClean': 'Moderne & Épuré',
    'brief.styleClassicProfessional': 'Classique & Professionnel',
    'brief.styleBoldCreative': 'Audacieux & Créatif',
    'brief.styleMinimalist': 'Minimaliste',
    'brief.stylePlayfulFun': 'Ludique & Amusant',
    'brief.styleLuxury': 'Luxe & Élégant',
    'brief.primaryColor': 'Couleur principale',
    'brief.secondaryColor': 'Couleur secondaire',
    'brief.colorPreferences': 'Préférences de couleurs',
    'brief.fontPreference': 'Préférence de police',
    'brief.pagesSection': 'Pages à inclure',
    'brief.selectPages': 'Sélectionnez les pages dont vous avez besoin',
    'brief.pageHome': 'Accueil',
    'brief.pageAbout': 'À propos',
    'brief.pageServices': 'Services',
    'brief.pageProducts': 'Produits',
    'brief.pageContact': 'Contact',
    'brief.pageBlog': 'Blog',
    'brief.pageGallery': 'Galerie',
    'brief.pageTestimonials': 'Témoignages',
    'brief.pageFAQ': 'FAQ',
    'brief.pagePricing': 'Tarifs',
    'brief.pageTeam': 'Équipe',
    'brief.pageCareers': 'Carrières',
    'brief.pagePortfolio': 'Portfolio',
    'brief.pageShop': 'Boutique',
    'brief.pageBooking': 'Réservation',
    'brief.pageEvents': 'Événements',
    'brief.featuresSection': 'Fonctionnalités nécessaires',
    'brief.selectFeatures': 'Sélectionnez les fonctionnalités dont vous avez besoin',
    'brief.featureContactForm': 'Formulaire de contact',
    'brief.featureNewsletter': 'Inscription newsletter',
    'brief.featureSocialMedia': 'Intégration réseaux sociaux',
    'brief.featureLiveChat': 'Chat en direct',
    'brief.featureTestimonials': 'Section témoignages',
    'brief.featureGallery': 'Galerie photo',
    'brief.featureVideoPlayer': 'Lecteur vidéo',
    'brief.featureBlog': 'Système de blog',
    'brief.featureComments': 'Système de commentaires',
    'brief.featureSearch': 'Fonction de recherche',
    'brief.featureUserAccounts': 'Comptes utilisateurs',
    'brief.featureMembership': 'Système d\'adhésion',
    'brief.featureBooking': 'Système de réservation',
    'brief.featureAppointment': 'Planification de rendez-vous',
    'brief.featurePayments': 'Paiements en ligne',
    'brief.featureDonations': 'Dons',
    'brief.featureEcommerce': 'E-Commerce',
    'brief.featureInventory': 'Gestion des stocks',
    'brief.featureAnalytics': 'Tableau de bord analytique',
    'brief.featureMap': 'Intégration carte',
    'brief.featureMultilingual': 'Support multilingue',
    'brief.technicalSection': 'Exigences techniques',
    'brief.hostingPreference': 'Préférence d\'hébergement',
    'brief.domainName': 'Nom de domaine',
    'brief.haveDomain': 'J\'ai déjà un domaine',
    'brief.needDomain': 'J\'ai besoin d\'un nouveau domaine',
    'brief.sslCertificate': 'Certificat SSL',
    'brief.emailAccounts': 'Comptes email nécessaires',
    'brief.integrations': 'Intégrations tierces',
    'brief.selectIntegrations': 'Sélectionnez les intégrations nécessaires',
    'brief.seoSection': 'SEO & Marketing',
    'brief.seoRequired': 'Optimisation SEO requise',
    'brief.keywords': 'Mots-clés cibles',
    'brief.keywordsPlaceholder': 'Entrez les mots-clés séparés par des virgules',
    'brief.competitorUrls': 'URLs des sites concurrents',
    'brief.addCompetitor': 'Ajouter un concurrent',
    'brief.competitorName': 'Nom du concurrent',
    'brief.competitorUrl': 'URL du concurrent',
    'brief.competitorStrengths': 'Que font-ils bien?',
    'brief.competitorWeaknesses': 'Qu\'est-ce qui pourrait être amélioré?',
    'brief.brandSection': 'Ressources de marque',
    'brief.hasLogo': 'J\'ai un logo',
    'brief.hasBrandGuide': 'J\'ai des directives de marque',
    'brief.hasImages': 'J\'ai des images/contenu',
    'brief.hasContent': 'J\'ai du contenu rédigé',
    'brief.hasTestimonials': 'J\'ai des témoignages',
    'brief.uploadAssets': 'Télécharger les ressources de marque',
    'brief.timelineSection': 'Délai & Budget',
    'brief.preferredLaunch': 'Date de lancement préférée',
    'brief.budgetRange': 'Fourchette budgétaire',
    'brief.budgetUnder500': 'Moins de 500$',
    'brief.budget500to1000': '500$ - 1 000$',
    'brief.budget1000to2500': '1 000$ - 2 500$',
    'brief.budget2500to5000': '2 500$ - 5 000$',
    'brief.budget5000to10000': '5 000$ - 10 000$',
    'brief.budgetOver10000': 'Plus de 10 000$',
    'brief.budgetFlexible': 'Flexible / À discuter',
    'brief.paymentPreference': 'Préférence de paiement',
    'brief.paymentFull': 'Paiement intégral',
    'brief.paymentMilestones': 'Jalons',
    'brief.paymentMonthly': 'Mensuel',
    'brief.additionalComments': 'Commentaires supplémentaires',
    'brief.anyOtherRequirements': 'Autres exigences ou commentaires?',
    'brief.downloadPdf': 'Télécharger le brief en PDF',
    'brief.generating': 'Génération...',
    'brief.back': 'Retour',
    'brief.next': 'Suivant',
    'brief.submitBrief': 'Soumettre le brief',
    'brief.briefSaved': 'Brief enregistré avec succès!',
    'brief.fillAllFields': 'Veuillez remplir tous les champs requis',
    
    // Common Extended
    'common.notAvailable': 'N/D',
    'common.selectOption': 'Sélectionner une option',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.none': 'Aucun',
    'common.all': 'Tout',
    'common.other': 'Autre',
    'common.required': 'Requis',
    'common.optional': 'Optionnel',
  },
  
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.dashboard': 'Panel',
    'nav.discover': 'Descubrir',
    'nav.workspaces': 'Espacios de trabajo',
    'nav.admin': 'Admin',
    'nav.getStarted': 'Comenzar',
    'nav.pricing': 'Precios',
    'nav.contact': 'Contacto',
    
    // Auth
    'auth.signIn': 'Iniciar sesión',
    'auth.signUp': 'Registrarse',
    'auth.signOut': 'Cerrar sesión',
    'auth.email': 'Email',
    'auth.password': 'Contraseña',
    'auth.createAccount': 'Crear cuenta',
    
    // Hero
    'hero.title': 'Encuentra negocios sin sitio web',
    'hero.subtitle': 'Ayúdalos a crecer en línea con desarrollo web profesional',
    'hero.searchPlaceholder': 'Ingresa ciudad, área o dirección...',
    'hero.searchButton': 'Buscar negocios',
    
    // Services
    'services.title': 'Lo que ofrecemos',
    'services.businessWebsites': 'Sitios web empresariales',
    'services.ecommerceStores': 'Tiendas online',
    
    // Packages
    'package.title': 'Elige tu paquete',
    'package.standard': 'Estándar',
    'package.pro': 'Pro',
    'package.premium': 'Premium',
    
    // Common
    'common.loading': 'Cargando...',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    
    // Language
    'language.selectLanguage': 'Seleccionar idioma',
    'language.english': 'Inglés',
    'language.french': 'Francés',
    'language.spanish': 'Español',
    'language.portuguese': 'Portugués',
    'language.arabic': 'Árabe',
    'language.swahili': 'Suajili',
    
    // Pricing
    'pricing.getStarted': 'Comenzar',
    'pricing.oneTime': 'único',
    'pricing.transparent': 'Precios transparentes',
    
    // Footer
    'footer.rights': 'Todos los derechos reservados.',
    'footer.needHelp': '¿Necesitas ayuda? Contacta',
    
    // Stats
    'stats.projectsDelivered': 'Proyectos entregados',
    'stats.happyClients': 'Clientes satisfechos',
    
    // Time
    'time.justNow': 'Justo ahora',
    'time.today': 'Hoy',
    'time.yesterday': 'Ayer',
  },
  
  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.dashboard': 'Painel',
    'nav.discover': 'Descobrir',
    'nav.workspaces': 'Espaços de trabalho',
    'nav.admin': 'Admin',
    'nav.getStarted': 'Começar',
    'nav.pricing': 'Preços',
    'nav.contact': 'Contato',
    
    // Auth
    'auth.signIn': 'Entrar',
    'auth.signUp': 'Registrar',
    'auth.signOut': 'Sair',
    'auth.email': 'Email',
    'auth.password': 'Senha',
    'auth.createAccount': 'Criar conta',
    
    // Hero
    'hero.title': 'Encontre negócios sem site',
    'hero.subtitle': 'Ajude-os a crescer online com desenvolvimento web profissional',
    'hero.searchPlaceholder': 'Digite cidade, área ou endereço...',
    'hero.searchButton': 'Buscar negócios',
    
    // Services
    'services.title': 'O que oferecemos',
    'services.businessWebsites': 'Sites empresariais',
    'services.ecommerceStores': 'Lojas online',
    
    // Packages
    'package.title': 'Escolha seu pacote',
    'package.standard': 'Padrão',
    'package.pro': 'Pro',
    'package.premium': 'Premium',
    
    // Common
    'common.loading': 'Carregando...',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.back': 'Voltar',
    'common.next': 'Próximo',
    
    // Language
    'language.selectLanguage': 'Selecionar idioma',
    'language.english': 'Inglês',
    'language.french': 'Francês',
    'language.spanish': 'Espanhol',
    'language.portuguese': 'Português',
    'language.arabic': 'Árabe',
    'language.swahili': 'Suaíli',
    
    // Pricing
    'pricing.getStarted': 'Começar',
    'pricing.oneTime': 'único',
    'pricing.transparent': 'Preços transparentes',
    
    // Footer
    'footer.rights': 'Todos os direitos reservados.',
    'footer.needHelp': 'Precisa de ajuda? Contate',
    
    // Stats
    'stats.projectsDelivered': 'Projetos entregues',
    'stats.happyClients': 'Clientes satisfeitos',
    
    // Time
    'time.justNow': 'Agora mesmo',
    'time.today': 'Hoje',
    'time.yesterday': 'Ontem',
  },
  
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.dashboard': 'لوحة التحكم',
    'nav.discover': 'اكتشف',
    'nav.workspaces': 'مساحات العمل',
    'nav.admin': 'المسؤول',
    'nav.getStarted': 'ابدأ',
    'nav.pricing': 'الأسعار',
    'nav.contact': 'اتصل',
    
    // Auth
    'auth.signIn': 'تسجيل الدخول',
    'auth.signUp': 'التسجيل',
    'auth.signOut': 'تسجيل الخروج',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.createAccount': 'إنشاء حساب',
    
    // Hero
    'hero.title': 'ابحث عن الشركات بدون مواقع',
    'hero.subtitle': 'ساعدهم على النمو عبر الإنترنت مع تطوير ويب احترافي',
    'hero.searchPlaceholder': 'أدخل المدينة أو المنطقة أو العنوان...',
    'hero.searchButton': 'بحث عن الشركات',
    
    // Services
    'services.title': 'ما نقدمه',
    'services.businessWebsites': 'مواقع الشركات',
    'services.ecommerceStores': 'متاجر إلكترونية',
    
    // Packages
    'package.title': 'اختر باقتك',
    'package.standard': 'قياسي',
    'package.pro': 'احترافي',
    'package.premium': 'متميز',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    
    // Language
    'language.selectLanguage': 'اختر اللغة',
    'language.english': 'الإنجليزية',
    'language.french': 'الفرنسية',
    'language.spanish': 'الإسبانية',
    'language.portuguese': 'البرتغالية',
    'language.arabic': 'العربية',
    'language.swahili': 'السواحلية',
    
    // Pricing
    'pricing.getStarted': 'ابدأ',
    'pricing.oneTime': 'لمرة واحدة',
    'pricing.transparent': 'أسعار شفافة',
    
    // Footer
    'footer.rights': 'جميع الحقوق محفوظة.',
    'footer.needHelp': 'تحتاج مساعدة؟ اتصل',
    
    // Stats
    'stats.projectsDelivered': 'المشاريع المسلمة',
    'stats.happyClients': 'العملاء السعداء',
    
    // Time
    'time.justNow': 'الآن',
    'time.today': 'اليوم',
    'time.yesterday': 'أمس',
  },
  
  sw: {
    // Navigation
    'nav.home': 'Nyumbani',
    'nav.dashboard': 'Dashibodi',
    'nav.discover': 'Gundua',
    'nav.workspaces': 'Nafasi za Kazi',
    'nav.admin': 'Msimamizi',
    'nav.getStarted': 'Anza',
    'nav.pricing': 'Bei',
    'nav.contact': 'Wasiliana',
    
    // Auth
    'auth.signIn': 'Ingia',
    'auth.signUp': 'Jisajili',
    'auth.signOut': 'Ondoka',
    'auth.email': 'Barua Pepe',
    'auth.password': 'Nenosiri',
    'auth.createAccount': 'Unda Akaunti',
    
    // Hero
    'hero.title': 'Pata Biashara bila Tovuti',
    'hero.subtitle': 'Wasaidie kukua mtandaoni na maendeleo ya tovuti ya kitaalamu',
    'hero.searchPlaceholder': 'Ingiza jiji, eneo au anwani...',
    'hero.searchButton': 'Tafuta Biashara',
    
    // Services
    'services.title': 'Tunachotoa',
    'services.businessWebsites': 'Tovuti za Biashara',
    'services.ecommerceStores': 'Maduka ya Mtandaoni',
    
    // Packages
    'package.title': 'Chagua Kifurushi chako',
    'package.standard': 'Kawaida',
    'package.pro': 'Pro',
    'package.premium': 'Premium',
    
    // Common
    'common.loading': 'Inapakia...',
    'common.save': 'Hifadhi',
    'common.cancel': 'Ghairi',
    'common.back': 'Rudi',
    'common.next': 'Ifuatayo',
    
    // Language
    'language.selectLanguage': 'Chagua Lugha',
    'language.english': 'Kiingereza',
    'language.french': 'Kifaransa',
    'language.spanish': 'Kihispania',
    'language.portuguese': 'Kireno',
    'language.arabic': 'Kiarabu',
    'language.swahili': 'Kiswahili',
    
    // Pricing
    'pricing.getStarted': 'Anza',
    'pricing.oneTime': 'mara moja',
    'pricing.transparent': 'Bei wazi',
    
    // Footer
    'footer.rights': 'Haki zote zimehifadhiwa.',
    'footer.needHelp': 'Unahitaji msaada? Wasiliana',
    
    // Stats
    'stats.projectsDelivered': 'Miradi Iliyotumwa',
    'stats.happyClients': 'Wateja Walioridhika',
    
    // Time
    'time.justNow': 'Sasa hivi',
    'time.today': 'Leo',
    'time.yesterday': 'Jana',
  },
};

// Helper function to get nested translation
function getNestedValue(obj: Record<string, string>, key: string): string {
  const value = obj[key];
  if (value) return value;
  
  // Try to find a partial match
  const parts = key.split('.');
  let current: string | Record<string, string> = obj;
  
  for (const part of parts) {
    if (typeof current === 'string') return current;
    if (current[part] === undefined) return key;
    current = current[part] as string | Record<string, string>;
  }
  
  return typeof current === 'string' ? current : key;
}

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: 'en',
      setLanguage: (language) => set({ language }),
      t: (key) => {
        const state = get();
        const lang = state.language;
        const translation = translations[lang] || translations.en;
        return getNestedValue(translation, key) || key;
      },
    }),
    {
      name: 'webfinder-language',
      storage: createJSONStorage(() => localStorage),
      partialize: (state) => ({ language: state.language }),
    }
  )
);
